#!/bin/bash
#
# check_backup-cron: script para verificar existencias de copias de respaldo.
#
# (C) 2006 - 2026 NIS
# Autor: Martin Andres Gomez Gimenez <mggimenez@nis.com.ar>
# Distributed under the terms of the GNU General Public License v3
#



source /etc/backup-cron/backup-cron.conf
source /usr/libexec/backup-cron/backup-cron_functions.sh

TYPE="${2}"



function usage() {
  local PROGNAME
  PROGNAME=$(basename "$0")
  echo "${PROGNAME}:"
  echo "Verifica si se han realizado copias de seguridad mediante Backup-cron"
  echo
  echo "Uso: "
  echo "${PROGNAME} -t <TIPO>"
  echo
  echo "-t, --type      tipo de respaldo a verificar."
  echo
  echo "TIPO puede ser uno de los siguientes:"
  echo "  etc          respaldos realizados por backup_etc"
  echo "  home         respaldos realizados por backup_home"
  echo "  libvirt      respaldos realizados por backup_libvirt"
  echo "  mysql        respaldos realizados por backup_mysql"
  echo "  postgresql   respaldos realizados por backup_postgresql"
  echo "  usr          respaldos realizados por backup_usr"
  echo "  system       respaldos realizados por backup_raiz"
  echo "  var          respaldos realizados por backup_var"
}



function status() {
  local STATE=${1}

  case ${STATE} in
    0 )
      STATUS="Ok"
      echo "${STATUS}: backup ${DESC} was done without problems."
      return 0
      ;;
    [1-9] | 1[0-9] | 2[0-9] )
      STATUS="Warning"
      local PLURAL="s"
      (( STATE == 1 )) && PLURAL=""
      echo "${STATUS}: last backup ${DESC} was performed ${STATE} day${PLURAL} ago."
      return 1
      ;;
    30 )
      STATUS="Critical"
      echo "${STATUS}: there are no backups ${DESC} made in the last ${STATE} days."
      return 2
      ;;
    99 )
      STATUS="Critical"
      echo "${STATUS}: there are errors on backups ${DESC}."
      return 2
      ;;
    * )
      STATUS="Unknown"
      echo "${STATUS}."
      return 3
      ;;
  esac

}



if [ "${1}" != "-t" ] && [ "${1}" != "--type" ] || [ "${#}" != "2" ]; then
  usage
  status 99
  exit
fi



# Configuración de rutas de búsqueda.
BACKUP_PATH="${BACKUP_PATH}/${HOST}/${TYPE}"
FILE_BACKUP="backup-${HOST}-${TYPE}"
EXT=$(file_extension)

case ${TYPE} in
  etc )
      DESC="of /etc directory"
  ;;
  home )
      FILE_BACKUP="backup-${HOST}-${TYPE}-admin"
      DESC="of /home directory"
  ;;
  libvirt )
      FILE_BACKUP="$(virsh list --name | head -1)"
      EXT="qcow2"
      DESC="of virtual machines"
  ;;
  mysql )
      DESC="of MySQL databases"
  ;;
  postgresql )
      DESC="of PostgreSQL databases"
  ;;
  usr )
      FILE_BACKUP="backup-${HOST}-usr"
      DESC="of /usr directory"
  ;;
  system )
      FILE_BACKUP="backup-${HOST}-raiz"
      DESC="of system"
  ;;
  var )
      FILE_BACKUP="backup-${HOST}-var"
      DESC="of /var directory"
  ;;
  * )
    usage
    exit
  ;;
esac



# Extensiones utilizadas por los respaldos
EXT_REGEX="(${EXT//./\\.}|tar\.bz2)"
GPG_REGEX="${EXT_REGEX}(\.gpg)?$"

# Se busca el último backup realizado dentro de los últimos 30 días.
for i in {0..30}; do
  FECHA=$(date --date="${i} days ago" +%Y%m%d)
  MATCH_REGEX="${FILE_BACKUP}(|-full|-incremental)-${FECHA}\.${GPG_REGEX}"
  BACKUP=$(find "${BACKUP_PATH}" -maxdepth 1 -type f \
    -name "${FILE_BACKUP}*" 2>/dev/null | grep -E "${MATCH_REGEX}" | head -n 1)

  if [ -f "${BACKUP}" ]; then

      # Se verifica que los respaldos realizados se correspondan con el número
      # de bases de datos MySQL exitentes.
      if [ "${TYPE}" == "mysql" ]; then
        DB_NUM=$(show_databases_mysql "${BDB_USER}" "${BDB_PASSWD}" "${BDB_HOST}" | wc -l)
        FILE_BACKUP_DB_NUM=$(cat "${BACKUP}".list | wc -l)

        if [ "${DB_NUM}" -eq "${FILE_BACKUP_DB_NUM}" ]; then
            status "${i}"
            exit $?
          else
            status 99
            exit $?
        fi

        break
      fi

      # Se verifica que los respaldos realizados se correspondan con el número
      # de bases de datos PostgreSQL exitentes.
      if [ "${TYPE}" == "postgresql" ]; then
        export PGPASSWORD=${BDB_PG_PASSWD}
        DB_PG_NUM=$(show_databases_pg "${BDB_PG_USER}" "${BDB_PG_PASSWD}" "${BDB_PG_HOST}" | wc -l)
        FILE_BACKUP_PG_NUM=$(cat "${BACKUP}".list | wc -l)

        if [ "${DB_PG_NUM}" -eq "${FILE_BACKUP_PG_NUM}" ]; then
            status "${i}"
            exit $?
          else
            status 99
            exit $?
        fi

        break
      fi
      
      if [[ "${TYPE}" =~ ^(etc|home|libvirt|usr|system|var)$ ]]; then
          status 0
        else
          status "${i}"
          exit $?
      fi

      break
    else

      if (( i == 30 )); then
        status "${i}"
        exit $?
      fi

  fi

done

