#!/bin/bash
#
# clean_backup_home: script para borrar copias de respaldo obsoletas.
#
# (C) 2006 - 2026 NIS
# Autor: Martin Andres Gomez Gimenez <mggimenez@nis.com.ar>
# Distributed under the terms of the GNU General Public License v3
#



source /etc/backup-cron/backup-cron.conf
source /usr/libexec/backup-cron/backup-cron_functions.sh



NAME=$(basename "$0")

# Verifica si hay hosts configurados en /etc/backup-cron/backup-cron.conf, en el
# caso de no haberlos búsca en ${BACKUP_PATH}.
if [ "${HOSTS}" == "" ]; then
  HOSTS=$(ls -1 "${BACKUP_PATH}")
fi

# Creación de directorios inexistentes y borrado de copias de respaldos obsoletas.
for host in ${HOSTS}; do
  directory_mkdir "${BACKUP_PATH}"/"${host}"/home
  remove_incremental_backup "${BACKUP_PATH}"/"${host}"/home
done

rm -f /tmp/"${NAME}"-"${HOST}".txt

